//import Style
import "@/styles/main.scss";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { NextAuthProvider } from "./providersAuth";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Pada bagian ini adalah Root html dengan menggunakan provider dari NEXT-AUTH
  // untuk mengirimkan data session ke semua halaman
  return (
    <html lang="en">
      <body>
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  );
}
